my_chat:
    resource: "@MYChatBundle/Resources/config/routing.yml"
    prefix:   /

my_user:
    resource: "@MYUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"